name: Generate Snake Animation

on:
  schedule: # Runs at 8am UTC every day
    - cron: "0 8 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Generate Snake Animation
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: phohoccode
          output: dist/snake.svg

      - name: Push generated Snake animation to the output branch
        uses: actions/upload-artifact@v2
        with:
          name: snake.svg
          path: dist/snake.svg
